### ISSUE TITLE
!Инструкция

### ISSUE THREAD

**Issue by pavel-b-novikov** [AngelinaKa/nsudotnet#1]
Вы инструкцию-то прочитали по задачам?

**Comment by AngelinaKa** [comment]
## Конечно. Несколько раз. Но у меня возникли некоторые трудности 

Отправлено из мобильной Почты Mail.Ru
четверг, 07 мая 2015г., 12:19 +0600 от Pavel Novikov notifications@github.com:
Вы инструкцию-то прочитали по задачам?

**Comment by AngelinaKa** [comment]
## У меня приложение комп не тянет почему-то, а как там на сайте подпапку создать я понять не смогла. И не знаю как синхронизировать с visual studio. Я совсем новичок в этом деле, извините :( Стараюсь разобраться

Отправлено из мобильной Почты Mail.Ru
четверг, 07 мая 2015г., 12:19 +0600 от Pavel Novikov notifications@github.com:
Вы инструкцию-то прочитали по задачам?

**Comment by pavel-b-novikov** [comment]
Вы с мехмата?

**Comment by AngelinaKa** [comment]
## Нет, с физфака

Отправлено из мобильной Почты Mail.Ru
четверг, 07 мая 2015г., 12:54 +0600 от Pavel Novikov notifications@github.com:
Вы с мехмата?

**Comment by pavel-b-novikov** [comment]
Расфолловьте пожалуйста меня и подпишитесь на Семена:
https://github.com/sfactor

2015-05-07 12:54 GMT+06:00 Angelina Kabirova notifications@github.com:

> ## Нет, с физфака
> 
> Отправлено из мобильной Почты Mail.Ru
> четверг, 07 мая 2015г., 12:54 +0600 от Pavel Novikov <
> notifications@github.com>:
> Вы с мехмата?
> 
> —
> Reply to this email directly or  view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AngelinaKa/nsudotnet/issues/1#issuecomment-99748171.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by AngelinaKa** [comment]
## Ок, спасибо

Отправлено из мобильной Почты Mail.Ru
четверг, 07 мая 2015г., 13:17 +0600 от Pavel Novikov notifications@github.com:
Расфолловьте пожалуйста меня и подпишитесь на Семена:
https://github.com/sfactor
2015-05-07 12:54 GMT+06:00 Angelina Kabirova notifications@github.com:

**Comment by AngelinaKa** [comment]
## А дальше что?

Отправлено из мобильной Почты Mail.Ru
четверг, 07 мая 2015г., 13:17 +0600 от Pavel Novikov notifications@github.com:
Расфолловьте пожалуйста меня и подпишитесь на Семена:
https://github.com/sfactor
2015-05-07 12:54 GMT+06:00 Angelina Kabirova notifications@github.com:

**Comment by pavel-b-novikov** [comment]
Дальше напишите лектору белых лекций на почту (есть в группе на вк и на сайте), что хотите чтобы он вас проверил.
